import os

CODE_EXTENSIONS = [".py", ".js", ".jsx", ".ts", ".tsx", ".java", ".cs", ".html", ".css"]

AI_KEYWORDS = [
    "chatgpt",
    "openai",
    "generated by ai",
    "ai-generated",
    "copilot",
    "gemini",
    "claude",
]


def analyze_file(file_path):
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as file:
            lines = file.readlines()
    except Exception:
        return None

    total_lines = len(lines)
    if total_lines == 0:
        return None

    comment_lines = 0
    keyword_hits = 0

    for line in lines:
        stripped = line.strip().lower()

        if (
            stripped.startswith("#")
            or stripped.startswith("//")
            or stripped.startswith("/*")
            or stripped.startswith("*")
        ):
            comment_lines += 1

        for keyword in AI_KEYWORDS:
            if keyword in stripped:
                keyword_hits += 1

    comment_ratio = comment_lines / total_lines

    score = 0

    if total_lines > 150:
        score += 20

    if comment_ratio > 0.25:
        score += 25

    if keyword_hits > 0:
        score += 35

    if total_lines > 50 and comment_ratio < 0.03:
        score += 10

    if score > 100:
        score = 100

    return {
        "file": file_path,
        "lines": total_lines,
        "comment_ratio": round(comment_ratio * 100, 2),
        "keyword_hits": keyword_hits,
        "ai_score": score,
    }


def scan_project(root_dir):
    results = []

    for folder, _, files in os.walk(root_dir):
        if (
            ".git" in folder
            or "node_modules" in folder
            or "__pycache__" in folder
            or "ai-code-analysis" in folder
        ):
            continue

        for filename in files:
            if any(filename.endswith(ext) for ext in CODE_EXTENSIONS):
                file_path = os.path.join(folder, filename)
                result = analyze_file(file_path)
                if result:
                    results.append(result)

    return results


def create_report(results):
    total_score = 0

    with open("ai_report.md", "w", encoding="utf-8") as report:
        report.write("# AI Code Analysis Report\n\n")
        report.write("This report contains a demo-level static analysis of source code files.\n\n")
        report.write(
            "> Note: This tool does not provide definitive AI detection. It uses simple heuristic indicators for project documentation purposes.\n\n"
        )

        report.write("| File | Lines | Comment Ratio | AI Keyword Hits | AI Score |\n")
        report.write("|---|---:|---:|---:|---:|\n")

        for item in results:
            total_score += item["ai_score"]
            report.write(
                f"| {item['file']} | {item['lines']} | {item['comment_ratio']}% | {item['keyword_hits']} | {item['ai_score']}% |\n"
            )

        average_score = round(total_score / len(results), 2) if results else 0

        report.write("\n## Summary\n\n")
        report.write(f"Average estimated AI likelihood score: **{average_score}%**\n\n")

        if average_score <= 30:
            report.write("Result: Low AI-like pattern detected.\n")
        elif average_score < 60:
            report.write("Result: Medium AI-like pattern detected.\n")
        else:
            report.write("Result: High AI-like pattern detected.\n")


if __name__ == "__main__":
    project_path = ".."
    scan_results = scan_project(project_path)
    create_report(scan_results)
    print("AI code analysis completed. Report generated: ai_report.md")
